### ISSUE TITLE
How did you get the data?

### ISSUE THREAD

**Issue by stephenmm** [schust/wot-visualization#1]
I would like to re-run the data and I understand most of the code but it is not clear to me how you got the underlying data so that I could re-produce the results with more up-to-date tank data. Any help in this regard would be appreciated.

**Comment by schust** [comment]
Hey Stephen!
Thank you for your interest. This work is based on replays that I crawled from replay sites. I wrote my own Java program to do that. I haven't made that code public though. I'll give you some more details in a private message. Can you write me on reddit?
